# Generated by Django 4.0.3 on 2022-03-07 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LtiContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context_id",
                    models.CharField(
                        max_length=512,
                        unique=True,
                        verbose_name="LTI context ID (aka: course ID)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mux_id",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Mux direct upload URL ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "WAITING"),
                            ("asset_created", "CREATED"),
                            ("errored", "ERRORED"),
                            ("cancelled", "CANCELLED"),
                            ("timed_out", "TIMED_OUT"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "lti_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="muxltiproducer.lticontext",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mux_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Mux asset ID"
                    ),
                ),
                (
                    "lti_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="muxltiproducer.lticontext",
                    ),
                ),
            ],
        ),
    ]
